/**
 * ETERNO TATTOO STUDIO - PORTFOLIO DATABASE
 * Separated to improve initial script parsing performance.
 */

window.portfolioData = {
  '@dansrivastattoo': {
    'Retratos': [
      'Retratos/1.1.webp',
      'Retratos/1.2.webp',
      'Retratos/1.3.webp',
      'Retratos/2.webp',
      'Retratos/3.webp',
      'Retratos/44444.webp',
      'Retratos/IMG_1518.webp',
      'Retratos/IMG_3058.webp',
      'Retratos/IMG_3405.webp',
      'Retratos/IMG_3546.webp',
      'Retratos/IMG_8620.webp',
      'Retratos/jimmy.webp'
    ],
    'Fullcolor': [
      'fullcolor/4.webp',
      'fullcolor/1.webp', 'fullcolor/3.webp', 'fullcolor/5.webp',
      'fullcolor/6.1.webp', 'fullcolor/6.2.webp', 'fullcolor/6.webp', 'fullcolor/7.webp',
      'fullcolor/IMG_0280.webp', 'fullcolor/IMG_0845.webp', 'fullcolor/IMG_1350.webp',
      'fullcolor/IMG_2672.webp', 'fullcolor/IMG_3717.webp', 'fullcolor/IMG_4202.webp',
      'fullcolor/2.webp',
      'fullcolor/IMG_4984.webp', 'fullcolor/IMG_5360.webp', 'fullcolor/IMG_5429.webp',
      'fullcolor/IMG_5541.webp', 'fullcolor/IMG_5543.webp', 'fullcolor/IMG_5546.webp',
      'fullcolor/IMG_5911.webp', 'fullcolor/IMG_6014.webp', 'fullcolor/IMG_8026.webp',
      'fullcolor/IMG_9270.webp', 'fullcolor/IMG_9478.webp', 'fullcolor/IMG_9838.webp',
      'fullcolor/anme.webp', 'fullcolor/bruj.webp', 'fullcolor/calc.webp', 'fullcolor/cang.webp',
      'fullcolor/chiv.webp', 'fullcolor/dedpol.webp', 'fullcolor/ff7.webp', 'fullcolor/flor.webp',
      'fullcolor/flores.webp', 'fullcolor/fnix.webp', 'fullcolor/jrdn.webp', 'fullcolor/koku.webp',
      'fullcolor/leons.webp', 'fullcolor/mago.webp', 'fullcolor/nar.webp', 'fullcolor/pulp.webp',
      'fullcolor/red.webp', 'fullcolor/rosees.webp', 'fullcolor/rosescarta.webp', 'fullcolor/saw.webp',
      'fullcolor/tot.webp',
      'fullcolor/4444.webp', 'fullcolor/coralillo.webp', 'fullcolor/IMG_0281.webp',
      'fullcolor/IMG_7757.webp', 'fullcolor/oli.webp', 'fullcolor/penultimo.webp',
      'fullcolor/perico.webp', 'fullcolor/snjudas.webp', 'fullcolor/toto3.webp', 'fullcolor/ultimo.webp'
    ],
    'Japonés': [
      'Japones/8.webp', 'Japones/IMG_3471.webp', 'Japones/IMG_3472.webp', 'Japones/IMG_8244.webp',
      'Japones/maori.webp'
    ],
    'Blackwork and blackout': [
      'Blackwork and blackout/1.webp', 'Blackwork and blackout/10.1.webp', 'Blackwork and blackout/10.webp',
      'Blackwork and blackout/11.webp', 'Blackwork and blackout/12.webp', 'Blackwork and blackout/13.webp',
      'Blackwork and blackout/14.1.webp', 'Blackwork and blackout/14.5.webp', 'Blackwork and blackout/14.webp',
      'Blackwork and blackout/15.webp', 'Blackwork and blackout/16.webp', 'Blackwork and blackout/17.webp',
      'Blackwork and blackout/18.webp', 'Blackwork and blackout/19.webp', 'Blackwork and blackout/2.1.webp',
      'Blackwork and blackout/2.webp', 'Blackwork and blackout/20.webp', 'Blackwork and blackout/21.webp',
      'Blackwork and blackout/22.webp', 'Blackwork and blackout/23.webp', 'Blackwork and blackout/24.webp',
      'Blackwork and blackout/25.webp', 'Blackwork and blackout/26.webp', 'Blackwork and blackout/27.webp',
      'Blackwork and blackout/28.webp', 'Blackwork and blackout/3.webp', 'Blackwork and blackout/39.webp',
      'Blackwork and blackout/4.webp', 'Blackwork and blackout/40.webp', 'Blackwork and blackout/41.webp',
      'Blackwork and blackout/42.webp', 'Blackwork and blackout/43.webp', 'Blackwork and blackout/44.webp',
      'Blackwork and blackout/45.webp', 'Blackwork and blackout/46.webp', 'Blackwork and blackout/5.6.webp',
      'Blackwork and blackout/5.webp', 'Blackwork and blackout/6.webp', 'Blackwork and blackout/7.55.webp',
      'Blackwork and blackout/7.8.webp', 'Blackwork and blackout/7.webp', 'Blackwork and blackout/8.3.webp',
      'Blackwork and blackout/9.webp', 'Blackwork and blackout/IMG_0127.webp', 'Blackwork and blackout/IMG_0166.webp',
      'Blackwork and blackout/IMG_0262.webp', 'Blackwork and blackout/IMG_0282(1).webp', 'Blackwork and blackout/IMG_0312.webp',
      'Blackwork and blackout/IMG_0398.webp', 'Blackwork and blackout/IMG_1292.webp', 'Blackwork and blackout/IMG_1363.webp',
      'Blackwork and blackout/IMG_1393.webp', 'Blackwork and blackout/IMG_1552.webp', 'Blackwork and blackout/IMG_1648.webp',
      'Blackwork and blackout/IMG_1695.webp', 'Blackwork and blackout/IMG_1838.webp', 'Blackwork and blackout/IMG_1867.webp',
      'Blackwork and blackout/IMG_1942.webp', 'Blackwork and blackout/IMG_2133.webp', 'Blackwork and blackout/IMG_2134.webp',
      'Blackwork and blackout/IMG_2257.webp', 'Blackwork and blackout/IMG_2308.webp', 'Blackwork and blackout/IMG_2481.webp',
      'Blackwork and blackout/IMG_2531.webp', 'Blackwork and blackout/IMG_2539.webp', 'Blackwork and blackout/IMG_2560.webp',
      'Blackwork and blackout/IMG_2562.webp', 'Blackwork and blackout/IMG_2732.webp', 'Blackwork and blackout/IMG_2734.webp',
      'Blackwork and blackout/IMG_2736.webp', 'Blackwork and blackout/IMG_2741.webp', 'Blackwork and blackout/IMG_2793.webp',
      'Blackwork and blackout/IMG_2977.webp', 'Blackwork and blackout/IMG_3358.webp', 'Blackwork and blackout/IMG_3663.webp',
      'Blackwork and blackout/IMG_4306.webp', 'Blackwork and blackout/IMG_4399.webp', 'Blackwork and blackout/IMG_4594.webp',
      'Blackwork and blackout/IMG_4914.webp', 'Blackwork and blackout/IMG_4926.webp', 'Blackwork and blackout/IMG_4936.webp',
      'Blackwork and blackout/IMG_4954.webp', 'Blackwork and blackout/IMG_5636.webp', 'Blackwork and blackout/IMG_5687.webp',
      'Blackwork and blackout/IMG_6023.webp', 'Blackwork and blackout/IMG_6422.webp', 'Blackwork and blackout/IMG_6439.webp',
      'Blackwork and blackout/IMG_6529.webp', 'Blackwork and blackout/IMG_6603.webp', 'Blackwork and blackout/IMG_6653.webp',
      'Blackwork and blackout/IMG_6699(1).webp', 'Blackwork and blackout/IMG_6769.webp', 'Blackwork and blackout/IMG_6770.webp',
      'Blackwork and blackout/IMG_6837.webp', 'Blackwork and blackout/IMG_6956.webp', 'Blackwork and blackout/IMG_7332.webp',
      'Blackwork and blackout/IMG_7477.webp', 'Blackwork and blackout/IMG_8803.webp', 'Blackwork and blackout/IMG_9137.webp',
      'Blackwork and blackout/IMG_9401.webp', 'Blackwork and blackout/IMG_9891.webp', 'Blackwork and blackout/angel caido.webp',
      'Blackwork and blackout/angel.webp', 'Blackwork and blackout/hanya.webp'
    ],
    'Anime, toons & games': [
      'Anime, toons y games/1_resultado.webp', 'Anime, toons y games/10_resultado.webp', 'Anime, toons y games/11_resultado.webp',
      'Anime, toons y games/12_resultado.webp', 'Anime, toons y games/13_resultado.webp', 'Anime, toons y games/14_resultado.webp',
      'Anime, toons y games/15_resultado.webp', 'Anime, toons y games/16_resultado.webp', 'Anime, toons y games/18_resultado.webp',
      'Anime, toons y games/19_resultado.webp', 'Anime, toons y games/2_resultado.webp', 'Anime, toons y games/20_resultado.webp',
      'Anime, toons y games/21_resultado.webp', 'Anime, toons y games/22_resultado.webp', 'Anime, toons y games/23_resultado.webp',
      'Anime, toons y games/24_resultado.webp', 'Anime, toons y games/26_resultado.webp', 'Anime, toons y games/27_resultado.webp',
      'Anime, toons y games/28_resultado.webp', 'Anime, toons y games/29_resultado.webp', 'Anime, toons y games/3_resultado.webp',
      'Anime, toons y games/30_resultado.webp', 'Anime, toons y games/31_resultado.webp', 'Anime, toons y games/32_resultado.webp',
      'Anime, toons y games/33.5_resultado.webp', 'Anime, toons y games/33_resultado.webp', 'Anime, toons y games/34_resultado.webp',
      'Anime, toons y games/35_resultado.webp', 'Anime, toons y games/4_resultado.webp', 'Anime, toons y games/5_resultado.webp',
      'Anime, toons y games/5D7D6B5B-8F98-46A0-8C49-65272E189614_resultado.webp', 'Anime, toons y games/6_resultado.webp',
      'Anime, toons y games/7_resultado.webp', 'Anime, toons y games/8_resultado.webp', 'Anime, toons y games/9_resultado.webp',
      'Anime, toons y games/IMG_1296_resultado.webp', 'Anime, toons y games/IMG_1333_resultado.webp', 'Anime, toons y games/IMG_2669_resultado.webp',
      'Anime, toons y games/IMG_2807_resultado.webp', 'Anime, toons y games/IMG_2809_resultado.webp', 'Anime, toons y games/IMG_2823(1)_resultado.webp',
      'Anime, toons y games/IMG_2913_resultado.webp', 'Anime, toons y games/IMG_2941_resultado.webp', 'Anime, toons y games/IMG_2948_resultado.webp',
      'Anime, toons y games/IMG_2954_resultado.webp', 'Anime, toons y games/IMG_2973_resultado.webp', 'Anime, toons y games/IMG_3278_resultado.webp',
      'Anime, toons y games/IMG_3868_resultado.webp', 'Anime, toons y games/IMG_3899_resultado.webp', 'Anime, toons y games/IMG_5196_resultado.webp',
      'Anime, toons y games/IMG_5449_resultado.webp', 'Anime, toons y games/IMG_5935_resultado.webp', 'Anime, toons y games/IMG_6174_resultado.webp',
      'Anime, toons y games/IMG_6290_resultado.webp', 'Anime, toons y games/IMG_6297_resultado.webp', 'Anime, toons y games/IMG_6306_resultado.webp',
      'Anime, toons y games/IMG_6656_resultado.webp', 'Anime, toons y games/IMG_7902_resultado.webp', 'Anime, toons y games/IMG_7907_resultado.webp',
      'Anime, toons y games/IMG_8135_resultado.webp', 'Anime, toons y games/IMG_8136_resultado.webp', 'Anime, toons y games/IMG_8147_resultado.webp',
      'Anime, toons y games/IMG_8571_resultado.webp', 'Anime, toons y games/IMG_8692_resultado.webp', 'Anime, toons y games/IMG_8696_resultado.webp',
      'Anime, toons y games/IMG_8977_resultado.webp', 'Anime, toons y games/IMG_9477_resultado.webp', 'Anime, toons y games/IMG_9793_resultado.webp',
      'Anime, toons y games/adri_resultado.webp', 'Anime, toons y games/joker_resultado.webp', 'Anime, toons y games/malef_resultado.webp',
      'Anime, toons y games/mona china_resultado.webp', 'Anime, toons y games/one piece_resultado.webp', 'Anime, toons y games/pikachu_resultado.webp',
      'Anime, toons y games/samurai_resultado.webp', 'Anime, toons y games/sukuna_resultado.webp'
    ],
    'Realismos': [
      'Realismos/1.webp', 'Realismos/1.2.webp', 'Realismos/1.4.webp',
      'Realismos/2.webp', 'Realismos/2.3.webp', 'Realismos/3.webp', 'Realismos/4.webp',
      'Realismos/5.webp', 'Realismos/6.webp', 'Realismos/7.webp', 'Realismos/8.webp',
      'Realismos/9.webp', 'Realismos/10.webp', 'Realismos/11.webp', 'Realismos/12.webp',
      'Realismos/13.webp', 'Realismos/14.webp', 'Realismos/16.webp', 'Realismos/17.webp',
      'Realismos/18.webp', 'Realismos/19.webp', 'Realismos/21.webp', 'Realismos/22.webp',
      'Realismos/23.webp', 'Realismos/24.webp', 'Realismos/25.webp', 'Realismos/26.webp',
      'Realismos/27.webp', 'Realismos/cartas.webp', 'Realismos/cruz.webp',
      'Realismos/IMG_0029.webp', 'Realismos/IMG_0155.webp', 'Realismos/IMG_0278(1).WEBP',
      'Realismos/IMG_0283.webp', 'Realismos/IMG_0615.webp', 'Realismos/IMG_1216.webp',
      'Realismos/IMG_1256.webp', 'Realismos/IMG_1292(1).webp', 'Realismos/IMG_1320.webp',
      'Realismos/IMG_1428.webp', 'Realismos/IMG_1476.webp', 'Realismos/IMG_1560.webp',
      'Realismos/IMG_1698(2).webp', 'Realismos/IMG_2642.webp', 'Realismos/IMG_2893.webp',
      'Realismos/IMG_2933.webp', 'Realismos/IMG_2989.webp', 'Realismos/IMG_3929.webp',
      'Realismos/IMG_5696.webp', 'Realismos/IMG_5708.webp', 'Realismos/IMG_5881.webp',
      'Realismos/IMG_6243.webp', 'Realismos/IMG_6244.webp', 'Realismos/IMG_6510.webp',
      'Realismos/IMG_6735.webp', 'Realismos/IMG_8002.webp', 'Realismos/IMG_8932.webp',
      'Realismos/IMG_9208.webp', 'Realismos/IMG_9447(1).webp', 'Realismos/IMG_9472.webp',
      'Realismos/IMG_0278(1)_1.webp'
    ],
    'Línea fina y Puntillismo': [
      'Línea fina y Puntillismo/1.webp', 'Línea fina y Puntillismo/2.webp', 'Línea fina y Puntillismo/3.webp',
      'Línea fina y Puntillismo/5.webp', 'Línea fina y Puntillismo/5.5.webp', 'Línea fina y Puntillismo/6.webp',
      'Línea fina y Puntillismo/7.webp', 'Línea fina y Puntillismo/8.webp', 'Línea fina y Puntillismo/9.webp',
      'Línea fina y Puntillismo/10.webp', 'Línea fina y Puntillismo/10.1.webp',
      'Línea fina y Puntillismo/11.webp', 'Línea fina y Puntillismo/12.webp', 'Línea fina y Puntillismo/12.webp',
      'Línea fina y Puntillismo/13.webp', 'Línea fina y Puntillismo/14.webp', 'Línea fina y Puntillismo/15.webp',
      'Línea fina y Puntillismo/16.webp', 'Línea fina y Puntillismo/16.5.webp',
      'Línea fina y Puntillismo/17.webp', 'Línea fina y Puntillismo/17.1.webp',
      'Línea fina y Puntillismo/18.webp', 'Línea fina y Puntillismo/19.webp',
      'Línea fina y Puntillismo/20.webp', 'Línea fina y Puntillismo/21.webp',
      'Línea fina y Puntillismo/22.webp', 'Línea fina y Puntillismo/23.webp',
      'Línea fina y Puntillismo/24.webp', 'Línea fina y Puntillismo/25.webp',
      'Línea fina y Puntillismo/26.webp', 'Línea fina y Puntillismo/27.webp',
      'Línea fina y Puntillismo/28.webp', 'Línea fina y Puntillismo/29.webp',
      'Línea fina y Puntillismo/30.webp', 'Línea fina y Puntillismo/31.webp',
      'Línea fina y Puntillismo/32.webp', 'Línea fina y Puntillismo/333.webp',
      'Línea fina y Puntillismo/40.webp', 'Línea fina y Puntillismo/41.webp',
      'Línea fina y Puntillismo/43.webp', 'Línea fina y Puntillismo/44.webp',
      'Línea fina y Puntillismo/IMG_0013.webp', 'Línea fina y Puntillismo/IMG_0018.webp',
      'Línea fina y Puntillismo/IMG_0115.webp', 'Línea fina y Puntillismo/IMG_0116.webp',
      'Línea fina y Puntillismo/IMG_0117.webp', 'Línea fina y Puntillismo/IMG_0118.webp',
      'Línea fina y Puntillismo/IMG_0119.webp', 'Línea fina y Puntillismo/IMG_0120.webp',
      'Línea fina y Puntillismo/IMG_0121.webp', 'Línea fina y Puntillismo/IMG_0122.webp',
      'Línea fina y Puntillismo/IMG_0123.webp', 'Línea fina y Puntillismo/IMG_0124.webp',
      'Línea fina y Puntillismo/IMG_0252.webp', 'Línea fina y Puntillismo/IMG_0387.webp',
      'Línea fina y Puntillismo/IMG_0419.webp', 'Línea fina y Puntillismo/IMG_0470.webp',
      'Línea fina y Puntillismo/IMG_0742.webp', 'Línea fina y Puntillismo/IMG_0826.webp',
      'Línea fina y Puntillismo/IMG_1107.webp', 'Línea fina y Puntillismo/IMG_1136.webp',
      'Línea fina y Puntillismo/IMG_1155.webp', 'Línea fina y Puntillismo/IMG_1156.webp',
      'Línea fina y Puntillismo/IMG_1159.webp', 'Línea fina y Puntillismo/IMG_1162.webp',
      'Línea fina y Puntillismo/IMG_1204.webp', 'Línea fina y Puntillismo/IMG_1293.webp',
      'Línea fina y Puntillismo/IMG_1331.webp', 'Línea fina y Puntillismo/IMG_1388.webp',
      'Línea fina y Puntillismo/IMG_1412.webp', 'Línea fina y Puntillismo/IMG_1450.webp',
      'Línea fina y Puntillismo/IMG_1672.webp', 'Línea fina y Puntillismo/IMG_1696.webp',
      'Línea fina y Puntillismo/IMG_1715.webp', 'Línea fina y Puntillismo/IMG_1752.webp',
      'Línea fina y Puntillismo/IMG_1784.webp', 'Línea fina y Puntillismo/IMG_1850.webp',
      'Línea fina y Puntillismo/IMG_1866.webp', 'Línea fina y Puntillismo/IMG_1886.webp',
      'Línea fina y Puntillismo/IMG_1918.webp', 'Línea fina y Puntillismo/IMG_1983.webp',
      'Línea fina y Puntillismo/IMG_2122.webp', 'Línea fina y Puntillismo/IMG_2211.webp',
      'Línea fina y Puntillismo/IMG_2553.webp', 'Línea fina y Puntillismo/IMG_2597.webp',
      'Línea fina y Puntillismo/IMG_2667.webp', 'Línea fina y Puntillismo/IMG_2721.webp',
      'Línea fina y Puntillismo/IMG_2725.webp', 'Línea fina y Puntillismo/IMG_2727.webp',
      'Línea fina y Puntillismo/IMG_2746.webp', 'Línea fina y Puntillismo/IMG_2778.webp',
      'Línea fina y Puntillismo/IMG_2805.webp', 'Línea fina y Puntillismo/IMG_2875.webp',
      'Línea fina y Puntillismo/IMG_2876.webp', 'Línea fina y Puntillismo/IMG_2880.webp',
      'Línea fina y Puntillismo/IMG_3278(1).webp', 'Línea fina y Puntillismo/IMG_3458.webp',
      'Línea fina y Puntillismo/IMG_3459.webp', 'Línea fina y Puntillismo/IMG_3692.webp',
      'Línea fina y Puntillismo/IMG_4004.webp', 'Línea fina y Puntillismo/IMG_4859.webp',
      'Línea fina y Puntillismo/IMG_4861.webp', 'Línea fina y Puntillismo/IMG_5015.webp',
      'Línea fina y Puntillismo/IMG_5028.webp', 'Línea fina y Puntillismo/IMG_5034.webp',
      'Línea fina y Puntillismo/IMG_5076.webp', 'Línea fina y Puntillismo/IMG_5094.webp',
      'Línea fina y Puntillismo/IMG_5100.webp', 'Línea fina y Puntillismo/IMG_5210.webp',
      'Línea fina y Puntillismo/IMG_5212.webp', 'Línea fina y Puntillismo/IMG_5214.webp',
      'Línea fina y Puntillismo/IMG_5249.webp', 'Línea fina y Puntillismo/IMG_5252.webp',
      'Línea fina y Puntillismo/IMG_5253.webp', 'Línea fina y Puntillismo/IMG_5299.webp',
      'Línea fina y Puntillismo/IMG_5511.webp', 'Línea fina y Puntillismo/IMG_5858.webp',
      'Línea fina y Puntillismo/IMG_6045.webp', 'Línea fina y Puntillismo/IMG_6056.webp',
      'Línea fina y Puntillismo/IMG_6484.webp', 'Línea fina y Puntillismo/IMG_6530.webp',
      'Línea fina y Puntillismo/IMG_6550.webp', 'Línea fina y Puntillismo/IMG_7379.webp',
      'Línea fina y Puntillismo/IMG_7380.webp', 'Línea fina y Puntillismo/IMG_7535.webp',
      'Línea fina y Puntillismo/IMG_7562.webp', 'Línea fina y Puntillismo/IMG_7570.webp',
      'Línea fina y Puntillismo/IMG_7577.webp', 'Línea fina y Puntillismo/IMG_7579.webp',
      'Línea fina y Puntillismo/IMG_7665.webp', 'Línea fina y Puntillismo/IMG_8351.webp',
      'Línea fina y Puntillismo/IMG_8424.webp', 'Línea fina y Puntillismo/IMG_8525(1).webp',
      'Línea fina y Puntillismo/IMG_8526.webp', 'Línea fina y Puntillismo/IMG_8543.webp',
      'Línea fina y Puntillismo/IMG_8567.webp', 'Línea fina y Puntillismo/IMG_8593.webp',
      'Línea fina y Puntillismo/IMG_8595.webp', 'Línea fina y Puntillismo/IMG_8597.webp',
      'Línea fina y Puntillismo/IMG_8600.webp', 'Línea fina y Puntillismo/IMG_8714.webp',
      'Línea fina y Puntillismo/IMG_8762.webp', 'Línea fina y Puntillismo/IMG_8907.webp',
      'Línea fina y Puntillismo/IMG_8932(1).webp', 'Línea fina y Puntillismo/IMG_8973.webp',
      'Línea fina y Puntillismo/IMG_8974.webp', 'Línea fina y Puntillismo/IMG_9115.webp',
      'Línea fina y Puntillismo/IMG_9155.webp', 'Línea fina y Puntillismo/IMG_9159.webp',
      'Línea fina y Puntillismo/IMG_9281.webp', 'Línea fina y Puntillismo/IMG_9298.webp',
      'Línea fina y Puntillismo/IMG_9300.webp', 'Línea fina y Puntillismo/IMG_9383.webp',
      'Línea fina y Puntillismo/IMG_9385.webp', 'Línea fina y Puntillismo/IMG_9488.webp',
      'Línea fina y Puntillismo/IMG_9525.webp', 'Línea fina y Puntillismo/IMG_9527.webp',
      'Línea fina y Puntillismo/IMG_9532.webp', 'Línea fina y Puntillismo/IMG_9537.webp',
      'Línea fina y Puntillismo/IMG_9569.webp', 'Línea fina y Puntillismo/IMG_9662.webp',
      'Línea fina y Puntillismo/IMG_9664(1).webp', 'Línea fina y Puntillismo/IMG_9734(1).webp',
      'Línea fina y Puntillismo/IMG_9887.webp', 'Línea fina y Puntillismo/IMG_9888.webp'
    ],
    'lettering y nombres': [
      'lettering y nombres/1.webp', 'lettering y nombres/2.webp', 'lettering y nombres/2.1.webp',
      'lettering y nombres/3.webp', 'lettering y nombres/4.webp', 'lettering y nombres/5.webp',
      'lettering y nombres/6.webp', 'lettering y nombres/7.webp', 'lettering y nombres/8.webp',
      'lettering y nombres/IMG_0046.webp', 'lettering y nombres/IMG_0102.webp',
      'lettering y nombres/IMG_1386.webp', 'lettering y nombres/IMG_1720.webp',
      'lettering y nombres/IMG_1758.webp', 'lettering y nombres/IMG_1759.webp',
      'lettering y nombres/IMG_2378.webp', 'lettering y nombres/IMG_2528.webp',
      'lettering y nombres/IMG_2595.webp', 'lettering y nombres/IMG_4119.webp',
      'lettering y nombres/IMG_5221.webp', 'lettering y nombres/IMG_5563.webp',
      'lettering y nombres/IMG_5745.webp', 'lettering y nombres/IMG_6561.webp',
      'lettering y nombres/IMG_6637.webp', 'lettering y nombres/IMG_6718.webp',
      'lettering y nombres/IMG_7438.webp', 'lettering y nombres/IMG_7479.webp',
      'lettering y nombres/IMG_8338.webp', 'lettering y nombres/IMG_8777.webp',
      'lettering y nombres/IMG_9044.webp', 'lettering y nombres/IMG_9251.webp',
      'lettering y nombres/IMG_9254.webp', 'lettering y nombres/IMG_9411.webp',
      'lettering y nombres/IMG_9413.webp'
    ]
  }
};
